version: "3.9"

networks:
  custom_network:
    driver: bridge
services:
  backend:
    build:
      context: ./src
      dockerfile: ./backend.Dockerfile
    networks:
      - custom_network
  postgres:
    image: postgres:13.7-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - custom_network
